---
- hosts: all
  remote_user: tuankhoin
  become: 'yes'
  tasks:
    - name: Update
      apt:
        update_cache: 'yes'

    - name: Install https-supported packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Adding gpg key
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Setting up stable repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu
 {{ ansible_distribution_release }} stable"

    - name: Re-update
      apt:
        update_cache: 'yes'

    - name: Intalling Docker Engine and containerd
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
